# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XeAYoFTMZcy4vJg35a4avwoL88MulR5c
"""

from IPython.display import clear_output


print("-"*16)
print(" Menu de vendas")
print("-"*16)

Burguer = ['X-burguer','X-Salada','X-Bacon']
Hamburguers ={'X-burguer': 10.50,'X-Salada': 12.00,'X-Bacon': 15.00}
drinks=['Suco','Refri','Creme']
Bebidas={'Suco': 7.00,'Refri': 4.50,'Creme': 8.00}
pedido=[]
Conta = 0
def conta():
    Conta = 0
    for a in pedido:
      if a in Hamburguers:
        Conta += Hamburguers[a]
      if a in Bebidas:
        Conta += Bebidas[a]
    return Conta
while True:
  print("Opções: \n[1] Hambuguers \n[2] Bebidas\n[3] Conta\n[4] Finalizar")
  opção = int(input('Oque deseja? '))
  clear_output()

  if(opção == 1):
    Count = 0
    opH = 0
    for a in Hamburguers:
      print(f'[{Count}] {a} = R${Hamburguers[a]}')
      Count += 1
    op = int(input('O que vai querer? '))
    pedido.insert(0,Burguer[op])
    clear_output()
    pedido.sort()
    for a in pedido:
      print(a, end=' ')
    print('\n')

  if(opção == 2):
    opB = 0
    Count = 0
    for a in drinks:
      print(f'[{Count}] {a} = R${Bebidas[a]}')
      Count += 1
    opb = int(input('Qual bebida deseja? '))
    pedido.insert(0,drinks[opb])
    clear_output()
    pedido.sort()
    for a in pedido:
      print(a, end=' ')
    print('\n')

  elif(opção == 3):
    print(f"R$ {conta()}")
  elif(opção == 4):
    break;
print("Você pediu: ", end='')
for a in pedido:
  print(a, end=' | ')
print(f'\nTotal:R$ {conta()}')